version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - agricoventas-network
    environment:
      - VITE_API_URL=http://localhost:3000
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - backend_uploads:/app/uploads
      - backend_logs:/app/logs
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=mongodb://mongodb:27017/agricoventas
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_placeholder}
      - JWT_EXPIRES_IN=24h
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET:-your_refresh_token_secret_placeholder}
      - REFRESH_TOKEN_EXPIRES_IN=7d
      - UPLOADS_DIR=/app/uploads
      - CORS_ORIGIN=http://localhost,http://localhost:80
      # AWS S3 environment variables
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET:-agricoventas-uploads}
    networks:
      - agricoventas-network
    restart: always

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=agricoventas
    networks:
      - agricoventas-network
    restart: always
    command: [--auth]

networks:
  agricoventas-network:
    driver: bridge

volumes:
  frontend_build:
  backend_uploads:
  backend_logs:
  mongodb_data:
  mongodb_config:
